services:
  nexus:
    image: sonatype/nexus3:3.68.1
    container_name: nexus
    networks:
      - cicd_network
    ports:
      - "${NEXUS_UI_PORT}:8081"
      - "${NEXUS_DOCKER_REGISTRY_PORT}:9080"
    volumes:
      - nexus_data:/nexus-data
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms512m -Xmx1536m -XX:MaxDirectMemorySize=1g
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:8081/service/rest/v1/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 120s

networks:
  cicd_network:
    external: true

volumes:
  nexus_data:
